### ISSUE TITLE
LogCat messages: "Plugin should use CordovaInterface.getThreadPool()"

### ISSUE THREAD

**Issue by frell** [Red-Folder/Cordova-Plugin-BackgroundService#19]
Hello,

Thanks for a great plugin. 

I've noticed lots of these sorts of messages in my Logcat. All works fine, but think it could be causing some UI lag. Any suggestions?

THREAD WARNING: exec() call to BackgroundServicePlugin.getStatus blocked the main thread for 25ms. Plugin should use CordovaInterface.getThreadPool().

Phonegap v3.0
Android : 4.3

**Comment by Red-Folder** [comment]
Issue moved to https://github.com/Red-Folder/bgs-core/issues/26
