### ISSUE TITLE
Strange NullPointerException

### ISSUE THREAD

**Issue by teusink** [Red-Folder/Cordova-Plugin-BackgroundService#22]
Hi, I have a strange NullPointerException when I close my app (navigator.app.exit). It happens to all my services. I double checked all my code with JSLint to check for some silly typos, but I cannot find anything.

All the services gets closed when exiting app. Android is restarting them after the app closes them, but still. It is not very nice :).

I have: PhoneGap 3.1.0, jQuery Mobile 1.3.2, and I am using your second to latest version of the Background 3.1.0 plugin (not the one with the register and deregister for updates).

I am rather stuck in where to find the cause of this issue, The log below does not point to any of my code.

Thanks in advance!

Log:
`11-23 16:31:15.695: D/BackgroundServicePluginLogic(20289): On Destroy Start
11-23 16:31:15.695: D/BackgroundServicePluginLogic(20289): Checking for services
11-23 16:31:15.695: D/BackgroundServicePluginLogic(20289): Found services
11-23 16:31:15.695: D/BackgroundServicePluginLogic(20289): Calling service.close()
11-23 16:31:15.695: D/ServiceDetails(20289): Close called
11-23 16:31:15.695: D/ServiceDetails(20289): Removing ServiceListener
11-23 16:31:15.800: D/ServiceDetails(20289): close failed
11-23 16:31:15.800: D/ServiceDetails(20289): java.lang.NullPointerException
11-23 16:31:15.800: D/ServiceDetails(20289): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ServiceDetails.close(BackgroundServicePluginLogic.java:454)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic.onDestroy(BackgroundServicePluginLogic.java:199)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePlugin.onDestroy(BackgroundServicePlugin.java:84)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:326)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at org.apache.cordova.CordovaWebView.handleDestroy(CordovaWebView.java:833)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:774)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.Activity.performDestroy(Activity.java:5302)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3614)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3645)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.ActivityThread.access$1200(ActivityThread.java:153)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.os.Looper.loop(Looper.java:137)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at java.lang.reflect.Method.invoke(Method.java:525)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
11-23 16:31:15.800: D/ServiceDetails(20289): 	at dalvik.system.NativeStart.main(Native Method)
11-23 16:31:15.804: D/ServiceDetails(20289): Ignoring exception - will continue
11-23 16:31:15.812: D/ServiceDetails(20289): Close finished
11-23 16:31:15.812: D/BackgroundServicePluginLogic(20289): Calling service.close()
11-23 16:31:15.812: D/ServiceDetails(20289): Close called
11-23 16:31:15.812: D/ServiceDetails(20289): Removing ServiceListener
11-23 16:31:15.812: D/BackgroundService(20289): Listener removed
11-23 16:31:15.812: D/ServiceDetails(20289): Removing ServiceConnection
11-23 16:31:15.816: D/ServiceDetails(20289): Close finished
11-23 16:31:15.816: D/BackgroundServicePluginLogic(20289): On Destroy Finish`

config.xml
`<feature name="BackgroundServicePlugin"><param name="android-package" value="com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePlugin" /></feature>`

AndroidManifest.xml (I have 3 services
`<service
			android:name="org.teusink.droidpapers.UpdateChecker" 
			android:enabled="true"
			android:exported="false">
			<intent-filter>
				<action android:name="org.teusink.droidpapers.UpdateChecker"/> 
			</intent-filter>
		</service>`

Javascript
`cordova.define('cordova/plugin/updatechecker', function (require, exports, module) {
	CreateBackgroundService('org.teusink.droidpapers.UpdateChecker', require, exports, module); // JSLint error "Missing 'new' is oke here
});`

and
`function serviceUpdateChecker(action, input) {
	var updatechecker = cordova.require('cordova/plugin/updatechecker');
	if (action === "getStatus") {
		updatechecker.getStatus(
			function (r) { handleUpdateCheckerSuccess(r); },
			function (e) { handleUpdateCheckerError(e); }
		);
	}
	// every command/action has his place here.
}`

How I call it:
'serviceUpdateChecker("getStatus"', "none");`

Then the Service gets started. But this services is never closed, unless explicitly commanded by the user, and not on app close. Same for all other services.

**Comment by Red-Folder** [comment]
Moved issue to new Repo -> https://github.com/Red-Folder/bgs-core/issues/27
