### ISSUE TITLE
Background service to capture current location

### ISSUE THREAD

**Issue by askeypuah32** [Red-Folder/Cordova-Plugin-BackgroundService#3]
Hi,

Can this background service plugin do location capture at background? I put code as below to the MyService but seem failed to get the location.

lm = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
                lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,0,0, mVeggsterLocationListener);

Thanks,

Puah.

**Comment by veernimbus** [comment]
Red-Folder, i am trying to write "lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,0,0, myLocationListner);" inside the do work method but it gives me an error saying that location cannot be fetched in the manner as i can't call looper.prepare() in this thread. Can you explain and help? I am new to java and android. 

Can i write this code inside doWork method ? 

// Acquire a reference to the system Location Manager
LocationManager locationManager = (LocationManager) this.getSystemService(Context.LOCATION_SERVICE);

// Define a listener that responds to location updates
LocationListener locationListener = new LocationListener() {
    public void onLocationChanged(Location location) {
         makeUseOfNewLocation(location);
    }

```
public void onStatusChanged(String provider, int status, Bundle extras) {}
public void onProviderEnabled(String provider) {}
public void onProviderDisabled(String provider) {}
```

  };

// Register the listener with the Location Manager to receive location updates
locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, locationListener);

**Comment by Red-Folder** [comment]
@veernimbus Firstly, please don't hijack closed issues.  Secondly, search through the issues - this has been answered before.

You can also look at my GPS plugin (see my repositories) or just search on Google - took me 5 minutes to find the answer when I need it
