### ISSUE TITLE
BackgroundService stops in android 4.4

### ISSUE THREAD

**Issue by acuatoria** [Red-Folder/Cordova-Plugin-BackgroundService#30]
I'm facing this issue , that seems when android kill the app also kill the service.
and I have read this http://stackoverflow.com/questions/20677781/in-android-4-4-swiping-app-out-of-recent-tasks-permanently-kills-application-wi

**Comment by Red-Folder** [comment]
Moved to new repo -> https://github.com/Red-Folder/bgs-core/issues/29
