### ISSUE TITLE
How to write multiple timers for one Service.

### ISSUE THREAD

**Issue by MaximShoustin** [Red-Folder/Cordova-Plugin-BackgroundService#36]
Hello,

1st of all thanks for great plugin. From example we have timer (by default 60 sec) that runs `doWork()` in loop every minute and use `updateHandler`. So far so good. 

What if I want to run additional timer lets say other Thread (on the same service `MyService`) that will run `doWork2()` each 6 min. Is it posible or I need to write my own. Sorry, don't want to reinvent the wheel.

Thanks,

**Comment by Red-Folder** [comment]
Moved to new repo -> https://github.com/Red-Folder/bgs-core/issues/30
