### ISSUE TITLE
Porting from another background plugin, how should I change my code?

### ISSUE THREAD

**Issue by galenthomasramos** [Red-Folder/Cordova-Plugin-BackgroundService#39]
I was using a background mode plugin found here: https://github.com/katzer/cordova-plugin-background-mode

But, after a few odd bugs that would arise at seemingly arbitrary moments in runtime, I have found that all that this plugin does is change a "keepRunning" flag so that Android will not kill the background activity. Unfortunately this still results in the javascript processes of my app to be killed eventually.

I would like to switch to this background plugin, however the implementation seems more involved than the one I was using before... I am wondering how I will go about changing my code to work with this plugin.

I use a local-notification plugin to add 14 notificaitons to be fired over two days. In order to register whether or not a user has accessed a notification or missed one, I set a condition in javascript that upon triggering a notification, if after three minutes the notification has not been clicked, then record that notification as having been missed.

Here are two event functions within the local-notificaiton plugin that achieve this:

    window.plugin.notification.local.ontrigger = function (id, state, json) {

        playNotificationAudio();

            setTimeout(function(){

                   if(didMissNotificationArr[id]){
                        window.plugin.notification.local.cancel(id);
                        registerAsMissedNotification(id);
                    }

                }, (180 * 1000));
            };

    window.plugin.notification.local.oncancel = function (id, state, json) {
                if(my_media){
                    my_media.stop();
                    my_media.release();
                    }
            };

I need background functionality so that the setTimeout() won't be killed, and therefore the notifications won't get registered as missed.

With your plugin, I see that doWork() is the main function that I will be using to execute these background services. I am wondering how I should cancel notifications after 3 minutes by using your plugin? The code I have now is all Javascript, and I see that doWork() should contain Java, so I am wondering if I should rewrite my app so that the cancelling function is performed through android calls within doWork(), or if there is a way to keep my javascript code working... there is quite a but more here that I didn't show in the above code and I would prefer to not have to rework all of it to work with this bgs plugin.

Thank you!

**Comment by Red-Folder** [comment]
No further traffic on this issue - thus closed
