### ISSUE TITLE
Possible to regard Android Phonegap app as foreground service?

### ISSUE THREAD

**Issue by galenthomasramos** [Red-Folder/Cordova-Plugin-BackgroundService#40]
So I may not know what I am talking about here, but I have been trying to brush up on Android in preparation for implementing your plugin when I cam across this helpful article:

http://www.vogella.com/tutorials/AndroidServices/article.html

The article states, "It is possible to assign services the same priority as foreground activities. In this case it is required to have a visible notification active for the related service. It is frequently used for services which play videos or music."

So in this situation, with foreground processes being the highest priority, my js application processes would not be terminated... In this way I should be able to keep my js code running in the background, as long as I implement this static notification within the notification tray, correct? Or is there way more to this than I am understanding?

**Comment by Red-Folder** [comment]
Merged in with issue on new repo -> https://github.com/Red-Folder/bgs-core/issues/17
