### ISSUE TITLE
Stopping service and closing app

### ISSUE THREAD

**Issue by joaopgrassi** [Red-Folder/Cordova-Plugin-BackgroundService#46]
I have implemented the background service plugin with an android phonegap app. When the user close the app, I call the following method:

    function stopService() {

    notificationService.getStatus(function (data) {
        
        if(data.ServiceRunning){
            notificationService.stopService(function (r) { console.log("service closed, now close the app"); navigator.app.exitApp(); },
                    function (e) { handleError(e) });
        }        
    }, function (e) {
        //todo
    });
    }

The app is closed but I see on LogCat several messages in this order:
07-02 17:33:54.186: D/BackgroundServicePluginLogic(1588): On Destroy Start
07-02 17:33:54.186: D/BackgroundServicePluginLogic(1588): Checking for services
07-02 17:33:54.186: D/BackgroundServicePluginLogic(1588): Found services
07-02 17:33:54.186: D/BackgroundServicePluginLogic(1588): Calling service.close()
07-02 17:33:54.186: D/ServiceDetails(1588): Close called
07-02 17:33:54.186: D/ServiceDetails(1588): Removing ServiceListener
07-02 17:33:54.186: D/BackgroundService(1588): Listener removed
07-02 17:33:54.186: D/ServiceDetails(1588): Removing ServiceConnection
07-02 17:33:54.196: D/ServiceDetails(1588): close failed
07-02 17:33:54.196: D/ServiceDetails(1588): java.lang.IllegalArgumentException: Service not registered: com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ServiceDetails$1@b66175c8
07-02 17:33:54.196: D/ServiceDetails(1588): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:891)

I could not find an example of stopping the service when closing the app, so I'm wondering if I have missed something. Thank you!

**Comment by Red-Folder** [comment]
Moves issue to new repo -> https://github.com/Red-Folder/bgs-core/issues/31
