### ISSUE TITLE
trying to bind a started BackgroundService

### ISSUE THREAD

**Issue by glopezdev** [Red-Folder/Cordova-Plugin-BackgroundService#48]
I found an issue while trying to bind an activity to a BackgroundService. It works fine when the service is started by activity.bindService but I will crash if the service is started explicitly with cordova.plugins.startService and throw the following exception:
```
FATAL EXCEPTION: main
Process: com.experiment.my_app, PID: 28693
 java.lang.NullPointerException
 	at android.os.Binder.queryLocalInterface(Binder.java:228)
 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServiceApi$Stub.asInterface(BackgroundServiceApi.java:26)
 	at com.red_folder.phonegap.plugin.backgroundservice.BackgroundServicePluginLogic$ServiceDetails$1.onServiceConnected(BackgroundServicePluginLogic.java:633)
 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1114)
 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1131)
 	at android.os.Handler.handleCallback(Handler.java:733)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:146)
 	at android.app.ActivityThread.main(ActivityThread.java:5602)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 	at dalvik.system.NativeStart.main(Native Method)
   Force finishing activity com.experiment.my_app/.MyApp 
```
It seems like the cause is that BackgroundService is already implementing an onBind function that I'm overwriting. I tried without luck to create a more complex onBind method that will check for some extras on the intent to decide whether to return my Binder or call super.onBind, but unfortunately this is not possible.
A simple way to reproduce my issue is to try to start the following service, there is no need for an activity to bind to it. Just trying to start it will make the app crash.

```
public class BGService extends BackgroundService{
  
  public BGService(){}

  private static List<String> buffer = new LinkedList<String>();
  private static final IBinder mBinder = new BGBinder();
  public static class BGBinder extends Binder {
    public List<String> getBuffer() {
      return buffer;
    }
  }
  @Override
  public IBinder onBind(Intent intent) {
    return mBinder;
  };
  
  @Override
  protected JSONObject doWork() {
    return new JSONObject(); 
  }

  @Override
  protected JSONObject getConfig() {
    return null;
  }
  @Override
  protected void setConfig(JSONObject config) {}
  
  @Override
  protected JSONObject initialiseLatestResult() {
    return null;
  }
}
```

**My concern here:**
Is there a way to bind an activity to a started BackgroundService?

**Comment by glopezdev** [comment]
I finally got it working, but not in the cleanest way. I can bind to the started BackgroundService, if I don't define my own binder, by doing so I don't really have access the service instance, so I ended up using static methods to communicate with the service (IMHO defeating the purpose of binding the service).  
I think there would be value on adding some public method to the BackgroundServiceApi.Stub to retrieve it's owner (the BackgroundService), so that clients can cast it to their implementation.

**Comment by Red-Folder** [comment]
What are you trying to achieve by working directly with the BackgroundServiceApi.Stub?

The plugin should be hiding that complexity away from the developer.

**Comment by glopezdev** [comment]
I'm trying to communicate with my plugin that extends BackgroundService without broadcasting intents. But I can't create my own binders or use messengers without interfering with the some of the plugin logic that relies on its own binder.

**Comment by Red-Folder** [comment]
Sorry, I'm not following what you are trying to achieve.

If you want to deviate from the standard plugin, then I'd suggest forking the repository and making the appropriate changes there
