### ISSUE TITLE
registerForUpdates not working after restart

### ISSUE THREAD

**Issue by shankar667** [Red-Folder/Cordova-Plugin-BackgroundService#50]
everything working good except registerForUpdates, here i need function registerForUpdates run even after restart,any solution?

**Comment by Red-Folder** [comment]
You can't run a JavaScript function on restart (I assume you mean restart of the phone).  While you can registerForBoot - which will start the background service - this plugin doesn't allow you to run any JavaScript code.

You need the app open to run JavaScript code.

**Comment by christocracy** [comment]
A Service can force-load the Activity, though this could be surprising to the user, since the Activity will be brought to the foreground.

```
private void forceMainActivityReload() {
        Log.w(TAG, "- Forcing main-activity reload");
        PackageManager pm = getPackageManager();
        Intent launchIntent = pm.getLaunchIntentForPackage(getApplicationContext().getPackageName());
        launchIntent.addFlags(Intent.FLAG_FROM_BACKGROUND);
        launchIntent.addFlags(Intent.FLAG_ACTIVITY_NO_USER_ACTION);
        launchIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION);
        startActivity(launchIntent);
    }

```

**Comment by Red-Folder** [comment]
Good update.  I agree this would be a surprise.  Not really for what the plugin was designed for ... but interesting adaption.

**Comment by shankar667** [comment]
thank you christocracy.
