### ISSUE TITLE
Cant set millisecounds on some devices.

### ISSUE THREAD

**Issue by ofek-mizrahi** [Red-Folder/Cordova-Plugin-BackgroundService#51]
Hello,
I've created a simple app with background service and it works great on my device.
But when i tried to install it on other devices (3 to be exact) i found out that despite I've set timeout of 20000. my TimerMillisecounds is 1200000.
I have no idea why.
Any suggestions?
Thank you

**Comment by Red-Folder** [comment]
No obvious reason why.  I'd suggest running in debut/ putting logcat output in to ensure that the value is being save into the background service

**Comment by Red-Folder** [comment]
No further work on this repo - please by bgs-core
