### ISSUE TITLE
doWork not firing in mobile screen lock state

### ISSUE THREAD

**Issue by shankar667** [Red-Folder/Cordova-Plugin-BackgroundService#52]
doWork not working in phone locked state except this everything excellent, please provide suggestions

I'm using cordova 3.7, plugin added from https://github.com/Red-Folder/bgs-core.git

I have tested in anndroid kitkat and lollipop version mobiles, same problem persists in both.

Thanks in advance.

**Comment by Red-Folder** [comment]
Apologies for the delay in response.

What do you get through the logcat?

Normally when asked this question, the developer is expecting their JavaScript to run when the screen is locked/ off.  This cannot happen as the JavaScript needs the app to be running.  The app will generally be suspended/ stopped if the screen is locked/ off.

All doWork() activity should be in Java - except anything you want to update the UI with

**Comment by shankar667** [comment]
Thank you for your response,

Regarding logcat: I didn't check logcat, I will check and let you know.

I did some implementations in myService class (Java), those are local notification and http post request for php server.
Http post request executes every one minute and php server storing the timestamp in database, and also run's local notification with doWork()

When I locked/off the mobile those thing's are not working until mobile unlock/on

**Comment by shankar667** [comment]
timestamp in database, and also local notification with doWork()

When I lock the mobile those thing's are not working until mobile unlock

**Comment by Red-Folder** [comment]
Again, what is happening with the logcat.  Please post the logcat when working and when the mobile is locked.

**Comment by pcalderoncity** [comment]
Hi, I have a similar problem. The background service stops when the phone screen is not on. But the issue only happens when the usb is unplugged.

any Ideas?

Thanks.

**Comment by christocracy** [comment]
It must be an OS issue.  Upgrade to latest Android

On Thursday, July 23, 2015, pcalderoncity notifications@github.com wrote:

> Hi, I have a similar problem. The background service stops when the phone
> screen is not on. But the issue only happens when the usb is unplugged.
> 
> any Ideas?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Red-Folder/Cordova-Plugin-BackgroundService/issues/52#issuecomment-124215689
> .

## 

Snet from Gmail Mobile

**Comment by pcalderoncity** [comment]
Hi, thanks for your reply but I don't think that, because my phone is a OS Android 4.1.2, Sony Xperia

**Comment by christocracy** [comment]
I've had several reports from this phone.  Seems like a bad phone to
develop with

On Thursday, July 23, 2015, pcalderoncity notifications@github.com wrote:

> Hi, thanks for your reply but I don't think that, because my phone is a OS
> Android 4.1.2, Sony Xperia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Red-Folder/Cordova-Plugin-BackgroundService/issues/52#issuecomment-124221719
> .

## 

Snet from Gmail Mobile

**Comment by Red-Folder** [comment]
Normal advice from me I'm afraid; log everything.  (Logcat is my normal preference, but without USB you will need something else).

Pretty much every time I look at this bug the background service is running fine - there is something wrong in the doWork() or subsequent code that is failing.

**Comment by pcalderoncity** [comment]
Thanks for your reply. I detected that the service is not working because my database log does not show activity when the phone  screen is not on. Every minute my service makes a request to the remote  database. As I said before the issue happens when the usb is unplugged. 

Thanks.

**Comment by Red-Folder** [comment]
How are you connecting to that remote database?

There could be various reasons why you are not seeing database activity (especially if remote) - most nothing to do with the background service plugin.  You need to write trace logs to the device to see what is happening (does the timer get triggered, if so what happens next, etc).

Have a search on Google - I believe there are libraries to write logcat output to file (perfect for when you are usb unplugged)

**Comment by pcalderoncity** [comment]
Sorry I expressed wrong. My service makes a call to the remote server through Rest api so always it must to do the call.

When I turn on the phone screen the service restarts normally without unlocking it and my server log shows that.

Thanks again.

**Comment by charmingarpit** [comment]
I am also having the exact same problem. I have Galaxy S6 Edge and whenever my phone is connected to USB port and I getting the logcats in my dev environment, the service is working fine even when screen is locked. But when the USB cable is disconnected from phone and PC, the service stops making calls to REST API which I have deployed in the backend, Please help. This problem is killing the use of the BG Service.

**Comment by pcalderoncity** [comment]
Hi charmingarpit, I fixed the problem with this:

1- Grant wakelock permission in manifest file.
<uses-permission android:name="android.permission.WAKE_LOCK" />

2- Insert code below in your backgroundservice class:

   static final String NAME = "com.blah.yourbackgroundService ";
    static final String LAST_ALARM = "lastAlarm";
    private static volatile PowerManager.WakeLock lockStatic = null;

```
synchronized private static PowerManager.WakeLock getLock(Context context) {
    if (lockStatic == null) {
        PowerManager mgr = (PowerManager) context.getSystemService(Context.POWER_SERVICE);
        lockStatic = mgr.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, NAME);
        lockStatic.setReferenceCounted(true);
    }
    return (lockStatic);
}

@Override
public int onStartCommand(Intent intent, int flags, int startId) {
    PowerManager.WakeLock lock = getLock(this.getApplicationContext());
    if (!lock.isHeld() || (flags & START_FLAG_REDELIVERY) != 0) {
        lock.acquire();
    }
    return super.onStartCommand(intent, flags, startId);
}

final protected void onHandleIntent(Intent intent) {
    try {
        doWorkWrapper();
    } finally {
        PowerManager.WakeLock lock = getLock(this.getApplicationContext());

        if (lock.isHeld()) {
            try {
                lock.release();
            } catch (Exception e) {
                Log.e(getClass().getSimpleName(), "Exception when releasing wakelock", e);
            }
        }
    }
}
```

good Luck!

**Comment by vista-54** [comment]
08 января 2016, 15:38:20, от "pcalderoncity" < notifications@github.com >: 

Hi charmingarpit, I fixed the problem with this: 1- Grant wakelock permission in manifest file. 
2- Insert code below in your backgroundservice class: static final String NAME = "com.blah.yourbackgroundService "; 
static final String LAST_ALARM = "lastAlarm"; 
private static volatile PowerManager.WakeLock lockStatic = null; synchronized private static PowerManager.WakeLock getLock(Context context) {
    if (lockStatic == null) {
        PowerManager mgr = (PowerManager) context.getSystemService(Context.POWER_SERVICE);
        lockStatic = mgr.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, NAME);
        lockStatic.setReferenceCounted(true);
    }
    return (lockStatic);
}

@Override
public int onStartCommand(Intent intent, int flags, int startId) {
    PowerManager.WakeLock lock = getLock(this.getApplicationContext());
    if (!lock.isHeld() || (flags & START_FLAG_REDELIVERY) != 0) {
        lock.acquire();
    }
    return super.onStartCommand(intent, flags, startId);
}

final protected void onHandleIntent(Intent intent) {
    try {
        doWorkWrapper();
    } finally {
        PowerManager.WakeLock lock = getLock(this.getApplicationContext());

```
    if (lock.isHeld()) {
        try {
            lock.release();
        } catch (Exception e) {
            Log.e(getClass().getSimpleName(), "Exception when releasing wakelock", e);
        }
    }
}
```

}

 good Luck! I try! Thanks

**Comment by charmingarpit** [comment]
Thanks @pcalderoncity and @vista-54 for the solution. It worked correctly.

**Comment by Red-Folder** [comment]
Please ensure that further work/ comments/ issues are again the bgs-core repo.  This repo is dead.
