### ISSUE TITLE
Wake Up Phone

### ISSUE THREAD

**Issue by zeeshanjan82** [Red-Folder/Cordova-Plugin-BackgroundService#53]
Is there any way using this plugin I could wake up the phone. My application is open but because of the Idle timout it has gone in locked state. How can I wake up the phone on an event.

**Comment by Red-Folder** [comment]
There are ways to wake the screen and (I think) turn off the screen lock.

It's been a while since I've tried.  Have a search on Google - you will find Java native code to do the job

**Comment by zeeshanjan82** [comment]
Thanks @Red-Folder Is it possible to use java native code inside my Cordova application for doing this task.

**Comment by Red-Folder** [comment]
Yes.  But it is reasonably advanced.  Have a search on Google and experiment
