### ISSUE TITLE
  How to run cordova plugin in Andriod background service using Cordova-Plugin-BackgroundService 

### ISSUE THREAD

**Issue by MuraliKrishnaDev** [Red-Folder/Cordova-Plugin-BackgroundService#54]
Hi,

I tried using redfolder background service plugin inorder to run a WifiWizard plugin -wifi scan,

How can I run this plugin? In a background service (Android and iOS)?

Please guide me on this on further process.

Thanks and regards,
Murali

**Comment by Red-Folder** [comment]
I'm not aware of the WifiWizard plugin.  If it is a Cordova/ Phonegap plugin then no you'll not be able to call it directly from the background service.  The Cordova/ Phonegap plugins use the middleware provided by the Cordova/ Phonegap environment - without it being in place (which it isn't when the background service is running & app is closed) then there is no method to communication between the plugins.  

You could probably rip the logic from the WifiWizard plugin and recreate as a background service - but that is beyond something I can tell you how to do.

Note that the background service plugin is Android only.
